apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dwh-query-executor
    app: query-executor-web
  name: query-executor
#  namespace: dwh-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dwh-query-executor
      app: query-executor-web  
      tier: frontend
      track: stable      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dwh-query-executor
        app: query-executor-web  
        tier: frontend
        track: stable      
    spec:
      containers:
      - env:
        - name: LOG_DIR
          value: /var/logs
        - name: SERVICE_PORT
          value: "8000"
        image: 10.50.4.110:5000/query-executor:dev
        imagePullPolicy: Always
        name: query-executor
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: repositorycred
#      restartPolicy: OnFailure

