"""identity added

Revision ID: 174df77eb551
Revises: 28f4f4a8aad2
Create Date: 2022-12-12 14:04:16.811457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174df77eb551'
down_revision = '28f4f4a8aad2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('identity_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'identity_id')
    # ### end Alembic commands ###
