"""initial

Revision ID: 28f4f4a8aad2
Revises: 
Create Date: 2022-11-29 20:11:32.554740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f4f4a8aad2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('db', sa.String(length=36), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=36), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_guid'), 'queries', ['guid'], unique=True)
    op.create_table('results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=True),
    sa.Column('dest_type', sa.String(length=36), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=36), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('access_creds', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_index(op.f('ix_queries_guid'), table_name='queries')
    op.drop_table('queries')
    # ### end Alembic commands ###
