"""altered queries table, db column has 728 chars instead of 36

Revision ID: e4c294f15700
Revises: 174df77eb551
Create Date: 2023-07-25 10:34:16.504057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c294f15700'
down_revision = '174df77eb551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queries', 'db',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=728),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queries', 'db',
               existing_type=sa.String(length=728),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
