apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "query-executor.fullname" . }}
  labels:
    {{- include "query-executor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "query-executor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "query-executor.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: "{{ .Chart.Name }}-migrations"
          image: "{{ printf "%s-migrations:%s" .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) }}"
          env:
            - name: DWH_QUERY_EXECUTOR_DB_MIGRATION_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "query-executor.fullname" . }}-secret
                  key: dwh_query_executor_db_migration_connection_string
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "query-executor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - secretRef:
                name: {{ include "query-executor.fullname" . }}-secret
            - configMapRef:
                name: {{ include "query-executor.fullname" . }}-configmap
          {{- if eq .Values.storageS3.storageClassName "ceph-bucket" }}
          env:
            - name: DWH_QUERY_EXECUTOR_MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-bucket
                  key: AWS_ACCESS_KEY_ID
            - name: DWH_QUERY_EXECUTOR_MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-bucket
                  key: AWS_SECRET_ACCESS_KEY
            - name: DWH_QUERY_EXECUTOR_MINIO_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-bucket
                  key: BUCKET_NAME
            - name: DWH_QUERY_EXECUTOR_MINIO_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-bucket
                  key: BUCKET_HOST
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
