{{- if eq .Values.storageS3.storageClassName "ceph-bucket" }}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ include "query-executor.fullname" . }}-bucket
  labels:
    {{- include "query-executor.labels" . | nindent 4 }}
spec:
  generateBucketName: {{ .Release.Name }}-bkt
  storageClassName: ceph-bucket
{{- end }}