apiVersion: v1
kind: Secret
metadata:
  name: {{ template "query-executor.fullname" . }}-secret
  labels:
    {{- include "query-executor.labels" . | nindent 4 }}
data:
  dwh_query_executor_db_connection_string: {{ .Values.secrets.db_connection_string }} # must be b64 encoded
  dwh_query_executor_db_migration_connection_string: {{ .Values.secrets.db_migration_connection_string }} # must be b64 encoded
  dwh_query_executor_db_sources_raw: {{ .Values.secrets.db_sources_raw }} # must be b64 encoded
  dwh_query_executor_db_sources_clickhouse: {{ .Values.secrets.db_sources_clickhouse }} # must be b64 encoded
  dwh_query_executor_db_connection_string_results: {{ .Values.secrets.db_connection_string_results }} # must be b64 encoded
  dwh_query_executor_minio_host: {{ .Values.secrets.minio_host }} # must be b64 encoded
  dwh_query_executor_minio_access_key: {{ .Values.secrets.minio_access_key }} # must be b64 encoded
  dwh_query_executor_minio_secret_key: {{ .Values.secrets.minio_secret_key }} # must be b64 encoded
  dwh_query_executor_minio_bucket_name: {{ .Values.secrets.minio_bucket_name }} # must be b64 encoded
  dwh_query_executor_mq_connection_string: {{ .Values.secrets.mq_connection_string }} # must be b64 encoded
type: Opaque